version: '3.8'

services:
  api:
    build: .
    container_name: one_time_secret_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    networks:
      - secret_network

  db:
    image: postgres:15
    container_name: one_time_secret_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secret_network

  redis:
    image: redis:7
    container_name: one_time_secret_cache
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - secret_network

networks:
  secret_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 