"""initial migration

Revision ID: initial
Create Date: 2023-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('passphrase_hash', sa.String(), nullable=True),
    sa.Column('is_accessed', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_secret_key'), 'secrets', ['secret_key'], unique=True)
    
    op.create_table('secret_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'DELETE', name='actiontype'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('additional_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_logs_secret_key'), 'secret_logs', ['secret_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_logs_secret_key'), table_name='secret_logs')
    op.drop_table('secret_logs')
    op.drop_index(op.f('ix_secrets_secret_key'), table_name='secrets')
    op.drop_table('secrets')
    # ### end Alembic commands ### 